/-
Copyright (c) 2025 Pointless Scheme Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Pointless Scheme Project
-/
import Mathlib.Order.CompleteBooleanAlgebra
import Mathlib.Order.Hom.CompleteLattice
import Mathlib.Order.Category.Frm

/-!
# Foundational Locale Theory

This file establishes the foundational theory of frames and locales needed for
pointless algebraic geometry.

## Main Definitions

Most definitions are re-exported from Mathlib:

* `Order.Frame` - A frame is a complete lattice satisfying the infinite distributive law
* `FrameHom` - Frame homomorphisms preserve arbitrary joins and finite meets
* `Frm` - The category of frames

## Design Decision: Concrete vs Abstract Frame Presentations

Mathematically, a frame can be presented by generators and relations:
  Fr⟨G | R⟩ = Free frame on G / frame congruence generated by R

Implementing this abstractly would require:
1. Construction of free frames on a set of generators
2. Frame congruences and quotient frames
3. Verification of the universal property

This is substantial infrastructure not currently in Mathlib.

**Our approach:** Instead of developing the full abstract theory, we prove concrete
theorems directly for `Rad R` (the frame of radical ideals):

* `Rad.radical_eq_sSup_basicOpen`: Shows `Rad R` is generated by basic opens D(f)
* `Rad.frameHom_eq_of_basicOpen_eq`: Frame homomorphisms from `Rad R` are determined
  by their action on basic opens (the universal property in concrete form)

This gives equivalent practical power for the Zariski locale without requiring
the full abstract machinery of frame presentations.

## References

* Blueprint: Chapter 1 - Foundational Locale Theory
* Johnstone, "Stone Spaces", Chapter II (for abstract frame presentations)
* Vickers, "Topology via Logic", Chapter 4
-/

open Order

namespace PointlessScheme

/-! ### Frames and Basic Structure

The following are re-exports and aliases from Mathlib for convenience.
-/

/-- A frame is a complete lattice satisfying the infinite distributive law:
    `a ⊓ ⨆ i, b i = ⨆ i, a ⊓ b i` -/
abbrev Frame := Order.Frame

/-- Frame homomorphisms preserve arbitrary joins and finite meets. -/
abbrev FrameHom' := _root_.FrameHom

/-! ### Frame Presentations (Mathematical Background)

A frame presentation Fr⟨G | R⟩ consists of:
- G: a set of generators
- R: a set of relations (equations between frame expressions over G)

The presented frame is the free frame on G quotiented by the frame congruence
generated by R.

**Universal Property:** A frame homomorphism f : Fr⟨G | R⟩ → L is uniquely
determined by a function φ : G → L that respects the relations R.

**Implementation Status:** We do not implement abstract frame presentations.
Instead, for the Zariski locale Rad(R), we prove concrete versions:

1. `Rad.radical_eq_sSup_basicOpen` shows that every radical ideal is the
   supremum of basic opens, i.e., Rad(R) is generated by {D(f) : f ∈ R}.

2. `Rad.frameHom_eq_of_basicOpen_eq` shows that a frame homomorphism from
   Rad(R) is uniquely determined by its action on basic opens.

These are the concrete manifestations of the universal property for our
specific frame of interest.
-/

/-- A frame presentation specifies generators and relations.

    **Note:** This is a data structure for describing presentations mathematically.
    We do not construct the presented frame from this data; instead, we prove
    concrete theorems for `Rad R` that establish the relevant properties directly.

    For a ring R, the Zariski frame Rad(R) has the implicit presentation:
    - Generators: D(f) for f ∈ R
    - Relations: D(1) = ⊤, D(0) = ⊥, D(fg) = D(f) ∧ D(g), etc.

    See `Rad.basicOpen_one`, `Rad.basicOpen_zero`, `Rad.basicOpen_mul` for these. -/
structure FramePresentation where
  /-- The type of generators -/
  Gen : Type*
  /-- The type of relations -/
  Rel : Type*
  /-- Left-hand side of each relation (as a predicate on generators) -/
  lhs : Rel → Gen → Prop
  /-- Right-hand side of each relation (as a predicate on generators) -/
  rhs : Rel → Gen → Prop

/-- The Zariski frame presentation for a ring R.

    Generators: Elements of R (representing basic opens D(f))
    Relations: The basic open identities

    **Note:** This describes the presentation; we don't construct the frame from it.
    The frame `Rad R` is constructed directly and proven to satisfy these properties. -/
def zariskiPresentation (R : Type*) : FramePresentation where
  Gen := R
  Rel := Unit  -- Simplified; actual relations are proven as theorems
  lhs := fun _ _ => True
  rhs := fun _ _ => True

/-! ### Key Theorems for the Zariski Locale

The following theorems (proven in `ZariskiLocale.lean`) establish that `Rad R`
behaves like the presented frame Fr⟨D(f) : f ∈ R | relations⟩:

* `Rad.basicOpen_one : basicOpen 1 = ⊤`
* `Rad.basicOpen_zero : basicOpen 0 = ⊥`
* `Rad.basicOpen_mul : basicOpen (f * g) = basicOpen f ⊓ basicOpen g`
* `Rad.basicOpen_pow : basicOpen (f ^ n) = basicOpen f` (for n ≥ 1)

The generation property:
* `Rad.radical_eq_sSup_basicOpen : I = ⨆ (f ∈ I), basicOpen f`

The universal property:
* `Rad.frameHom_eq_of_basicOpen_eq : (∀ r, f (basicOpen r) = g (basicOpen r)) → f = g`

These give us the practical benefits of frame presentations without needing
the full abstract construction.
-/

end PointlessScheme
